#!/usr/bin/env python3.6
# coding=utf-8

import logging
import os

# Логирование
FORMAT = '%(asctime)-15s %(levelname)s %(message)s'
logging.basicConfig(format=FORMAT)
logger = logging.getLogger('main')
logger.setLevel(logging.DEBUG)

root_dir = os.path.abspath(os.path.join(__file__, "../../.."))
docker_image = 'node:8.12.0-alpine'
theme_path = root_dir + '/vendor/politsturm/wordpress-theme'

logger.info("Собираем статику")

logger.info('Устанавливаем зависимости')
install_dependencies = 'docker run --rm -v %s:/var/www -w /var/www %s npm i' % (theme_path, docker_image)
logger.debug(install_dependencies)
os.system(install_dependencies)

logger.info('Собираем')
build_static = 'docker run --rm -v %s:/var/www -w /var/www %s ./node_modules/.bin/gulp' % (theme_path, docker_image)
logger.debug(build_static)
os.system(build_static)
