#!/usr/bin/env python3
# coding=utf-8

import logging
import os
from vendor.process import exec_command

# Логирование
FORMAT = '%(asctime)-15s %(levelname)s %(message)s'
logging.basicConfig(format=FORMAT)
logger = logging.getLogger('main')
logger.setLevel(logging.DEBUG)

root_dir = os.path.abspath(os.path.join(__file__, "../../.."))
docker_image = 'node:8.12.0-alpine'
theme_path = root_dir + '/vendor/politsturm/wordpress-theme'

logger.info("Собираем статику")

logger.info('Устанавливаем зависимости')
install_dependencies = 'docker run --user `id -u`:`id -g` --rm -v "%s:/var/www" -w /var/www "%s" npm i' % (theme_path, docker_image)
logger.debug(install_dependencies)
exec_command(install_dependencies)

logger.info('Собираем')
build_static = 'docker run --user `id -u`:`id -g` --rm -v "%s:/var/www" -w /var/www "%s" ./node_modules/.bin/gulp css' % (theme_path, docker_image)
logger.debug(build_static)
exec_command(build_static)
