#!/usr/bin/env python3
# coding=utf-8

import logging
import os
from vendor.process import exec_command

# Логирование
FORMAT = '%(asctime)-15s %(levelname)s %(message)s'
logging.basicConfig(format=FORMAT)
logger = logging.getLogger('main')
logger.setLevel(logging.DEBUG)

# Корень проекта
root_dir = os.path.abspath(os.path.join(__file__, "../../.."))
# Директория WP
wp_dir = root_dir + "/vendor/wordpress/wordpress"
# Директория в которой лежат плагины для копирования в WP
plugins_vendor_dir = root_dir + "/vendor/wordpress-plugin"
# Директория плагинов WP
plugins_destination_dir = wp_dir + "/wp-content/plugins"
# Директория тем WP
themes_destination_dir = wp_dir + "/wp-content/themes"

logger.info("Создаю символическую ссылку на тему")
theme_symlink_source = root_dir + '/vendor/politsturm/wordpress-theme'
theme_symlink_destination = themes_destination_dir + '/politsturm'
exec_command("rm -f '%s'" % theme_symlink_destination)
exec_command("ln -r -f -s '%s' '%s'" % (theme_symlink_source, theme_symlink_destination))
logger.debug("link: %s -> %s" % (theme_symlink_source, theme_symlink_destination))

logger.info("Создаю символическию ссылку на конфиг файл")
config_symlink_source = root_dir + '/wp-config.php'
config_symlink_destination = wp_dir + '/wp-config.php'
exec_command("rm -f '%s'" % config_symlink_destination)
exec_command("ln -r -f -s '%s' '%s'" % (config_symlink_source, config_symlink_destination))
logger.debug("link: %s -> %s" % (config_symlink_source, config_symlink_destination))

logger.info("Создаю символическию ссылку на картинки")
uploads_symlink_source = root_dir + '/runtime/uploads'
uploads_symlink_destination = wp_dir + '/wp-content/uploads'
exec_command("rm -f '%s'" % uploads_symlink_destination)
exec_command("ln -r -f -s '%s' '%s'" % (uploads_symlink_source, uploads_symlink_destination))
logger.debug("link: %s -> %s" % (uploads_symlink_source, uploads_symlink_destination))

logger.info("Создаю символические ссылкы на плагины")
for dir in os.listdir( plugins_vendor_dir ):
    plugin_from = plugins_vendor_dir + "/" + dir
    plugin_to = plugins_destination_dir + "/" + dir
    # если есть такая директория - пропускаем. Значит плагин поставили из админки
    exec_command("rm -f '%s'" % plugin_to)
    exec_command("ln -r -f -s '%s' '%s'" % (plugin_from, plugin_to))
    logger.debug("link: %s -> %s" % (plugin_from, plugin_to))
    logger.info("Создаю символические ссылки на плагин %s" % (dir))
