# Общая конфигурация docker-compose для основного приложения

version: '3.3'
services:
  nginx:
    image: nginx:1.15.6-alpine
    volumes:
    - ./etc/docker/services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./etc/docker/services/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    - ./etc/docker/services/nginx/conf.d/blocks/dummy_proxy.conf:/etc/nginx/conf.d/blocks/static_proxy_pass.conf
    - ./etc/docker/services/nginx/conf.d/blocks/restrictions.conf:/etc/nginx/conf.d/blocks/restrictions.conf
    - .:/var/www
    working_dir: /var/www
    env_file:
    - .env
    networks:
      default:
        aliases:
          - politsturm_nginx
  php:
    build: ./etc/docker/services/php/build
    volumes:
    - ./etc/docker/services/php/php.ini:/usr/local/etc/php/php.ini:ro
    - ./etc/docker/services/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    - .:/var/www
    working_dir: /var/www
    cap_add:
      - SYS_PTRACE
    env_file:
    - .env
    networks:
      default:
        aliases:
        - politsturm_wordpress
  mysql:
    build: ./etc/docker/services/mysql/build
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
    - ./etc/docker/services/mysql/conf.d/:/etc/mysql/conf.d/source/:ro
    env_file:
    - .env
    networks:
      default:
        aliases:
        - politsturm_mysql
