# Окружения для локальной разработки
# Используется по умолчанию

version: '3.3'
volumes:
  mysql_local_db:
services:
  proxy:
    restart: always
    build: ./etc/docker/services/proxy/build
    volumes:
    - ./etc/docker/services/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./etc/docker/services/proxy/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    - .:/var/www
    ports:
    - "8012:80"
    depends_on:
    - nginx
    env_file:
    - .env
    networks:
      default:
        aliases:
          - politsturm_proxy
    logging:
      driver: "syslog"
      options:
        syslog-facility: "local0"
        tag: "docker/politsturm/production/{{.Name}}"
  nginx:
    restart: always
    depends_on:
    - php
    logging:
      driver: "syslog"
      options:
        syslog-facility: "local0"
        tag: "docker/politsturm/production/{{.Name}}"
  php:
    restart: always
    volumes:
    - ./etc/docker/services/php/env/production.ini:/usr/local/etc/php/conf.d/production.ini:ro
    logging:
      driver: "syslog"
      options:
        syslog-facility: "local0"
        tag: "docker/politsturm/production/{{.Name}}"
  mysql:
    restart: always
    volumes:
    - /var/data/docker/politsturm/mysql/data:/var/lib/mysql
    ports:
    - "3309:3306"
    logging:
      driver: "syslog"
      options:
        syslog-facility: "local0"
        tag: "docker/politsturm/production/{{.Name}}"
